// <auto-generated />
using System;
using Assignment_ASP.NET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment_ASP.NET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251129103903_AddProductDetailFields")]
    partial class AddProductDetailFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment_ASP.NET.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Điện thoại"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Phụ kiện"
                        });
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.Coupon", b =>
                {
                    b.Property<int>("CouponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CouponID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponID = 1,
                            Code = "WELCOME",
                            DiscountPercentage = 10,
                            ExpiryDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            CouponID = 2,
                            Code = "SALE50",
                            DiscountPercentage = 50,
                            ExpiryDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailID"));

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("ntext");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KeyFeatures")
                        .HasColumnType("ntext");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specifications")
                        .HasColumnType("ntext");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("WarrantyPeriod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            Color = "Deep Purple",
                            Description = "Hàng chính hãng VN/A",
                            ImageUrl = "/images/iphone_14_promax.png",
                            Price = 27000000m,
                            ProductName = "iPhone 14 Pro Max",
                            Size = "256GB",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            Color = "Green",
                            Description = "Camera 200MP",
                            ImageUrl = "/images/galaxy_s23_ultra.png",
                            Price = 25000000m,
                            ProductName = "Samsung Galaxy S23 Ultra",
                            Size = "256GB",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 1,
                            Color = "White",
                            Description = "Chip MariSilicon",
                            ImageUrl = "/images/oppo_find_x5_pro.png",
                            Price = 18000000m,
                            ProductName = "Oppo Find X5 Pro",
                            Size = "128GB",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 1,
                            Color = "Black",
                            Description = "Hợp tác Leica",
                            ImageUrl = "/images/xiaomi_13.png",
                            Price = 15000000m,
                            ProductName = "Xiaomi 13",
                            Size = "128GB",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 1,
                            Color = "Blue",
                            Description = "Giá tốt",
                            ImageUrl = "/images/iphone_13.png",
                            Price = 17000000m,
                            ProductName = "iPhone 13",
                            Size = "128GB",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 1,
                            Color = "Beige",
                            Description = "Điện thoại gập",
                            ImageUrl = "/images/galaxy_zfold4.png",
                            Price = 30000000m,
                            ProductName = "Samsung Galaxy Z Fold 4",
                            Size = "256GB",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 1,
                            Color = "Snow",
                            Description = "Android thuần",
                            ImageUrl = "/images/pixel7_pro.png",
                            Price = 20000000m,
                            ProductName = "Google Pixel 7 Pro",
                            Size = "128GB",
                            StockQuantity = 10
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 1,
                            Color = "Red",
                            Description = "Pin trâu",
                            ImageUrl = "/images/iphone14_plus.png",
                            Price = 22000000m,
                            ProductName = "iPhone 14 Plus",
                            Size = "128GB",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 2,
                            Color = "White",
                            Description = "Chống ồn chủ động",
                            ImageUrl = "/images/ipod2_pro.png",
                            Price = 5500000m,
                            ProductName = "AirPods Pro 2",
                            Size = "N/A",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryID = 2,
                            Color = "White",
                            Description = "Sạc nhanh",
                            ImageUrl = "/images/apple_20w.png",
                            Price = 500000m,
                            ProductName = "Củ sạc Apple 20W",
                            Size = "20W",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductID = 11,
                            CategoryID = 2,
                            Color = "Black",
                            Description = "Thiết kế nhỏ gọn",
                            ImageUrl = "/images/galaxy_buds2.png",
                            Price = 2000000m,
                            ProductName = "Samsung Galaxy Buds 2",
                            Size = "N/A",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductID = 12,
                            CategoryID = 2,
                            Color = "Blue",
                            Description = "Chính hãng Apple",
                            ImageUrl = "/images/op_silicon_iphone14.png",
                            Price = 1000000m,
                            ProductName = "Ốp lưng iPhone 14 Silicon",
                            Size = "14 Pro Max",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductID = 13,
                            CategoryID = 2,
                            Color = "Black",
                            Description = "Siêu nhỏ gọn",
                            ImageUrl = "/images/anker_10000mah.png",
                            Price = 800000m,
                            ProductName = "Sạc dự phòng Anker 10000mAh",
                            Size = "10000mAh",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductID = 14,
                            CategoryID = 2,
                            Color = "White",
                            Description = "Dây dù",
                            ImageUrl = "/images/c_to_lightning.png",
                            Price = 300000m,
                            ProductName = "Cáp USB-C to Lightning",
                            Size = "1m",
                            StockQuantity = 300
                        },
                        new
                        {
                            ProductID = 15,
                            CategoryID = 2,
                            Color = "Graphite",
                            Description = "Chuột văn phòng",
                            ImageUrl = "/images/logitech_master3s.png",
                            Price = 2500000m,
                            ProductName = "Chuột Logitech MX Master 3S",
                            Size = "N/A",
                            StockQuantity = 50
                        });
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Employee"
                        },
                        new
                        {
                            RoleID = 3,
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Address = "123 Admin St, Da Nang",
                            Email = "admin@example.com",
                            FullName = "Admin User",
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "090111222",
                            RoleID = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserID = 2,
                            Address = "456 Employee St, Da Nang",
                            Email = "employee@example.com",
                            FullName = "Employee User",
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "090333444",
                            RoleID = 2,
                            Username = "employee"
                        },
                        new
                        {
                            UserID = 3,
                            Address = "789 Customer St, Da Nang",
                            Email = "customer@example.com",
                            FullName = "Customer User",
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "090555666",
                            RoleID = 3,
                            Username = "customer"
                        });
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.Order", b =>
                {
                    b.HasOne("Assignment_ASP.NET.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.OrderDetail", b =>
                {
                    b.HasOne("Assignment_ASP.NET.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment_ASP.NET.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.Product", b =>
                {
                    b.HasOne("Assignment_ASP.NET.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.Review", b =>
                {
                    b.HasOne("Assignment_ASP.NET.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment_ASP.NET.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.User", b =>
                {
                    b.HasOne("Assignment_ASP.NET.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Assignment_ASP.NET.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
